In [1]:
from collections import deque
from DQNAgent import DQNAgent
from snakegame import SnakeEnv
import numpy as np

/Users/vrishank/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
env = SnakeEnv(10,15)

In [3]:
env.state

array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [3, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 0, 3],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [ ]:
agent = DQNAgent()

/Users/vrishank/Desktop/snakegame/DQNAgent.py:25: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(16, (5, 5), input_shape=(1, 10, 15..., activation="relu", data_format="channels_first")`
  model.add(Conv2D(16, (5, 5), input_shape=(1, 10, 15), activation='relu', dim_ordering="th"))


In [ ]:
episodes = 10000
for e in range(episodes):
        state = env.reset()
        for time_t in range(500):
            action = agent.act(env.state.reshape(1, 1, 10, 15))
            next_state, reward, done = env.step(action)
            # Remember the previous state, action, reward, and done
            agent.remember(state, action, reward, next_state, done)
            # make next_state the new current state for the next frame.
            state = next_state
            if e%100 == 0:
                print(env.state)
            # done becomes True when the game ends
            if env.done:
                # print the score and break out of the loop
                print("episode: {}/{}, score: {}, time: {}"
                      .format(e, episodes, env.score, time_t))
                break
        # train the agent with the experience of the episode
        if e>20:
            agent.replay(32)

[[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 2 0 0 3]
 [3 0 0 0 0 0 2 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 1 1 1 1 1 1 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 2 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]]
episode: 0/10000, score: 0, time: 0
episode: 1/10000, score: 0, time: 3
episode: 2/10000, score: 0, time: 3
episode: 3/10000, score: 0, time: 0
episode: 4/10000, score: 0, time: 4
episode: 5/10000, score: 0, time: 2
episode: 6/10000, score: 0, time: 1
episode: 7/10000, score: 20, time: 11
episode: 8/10000, score: 0, time: 3
episode: 9/10000, score: 0, time: 2
episode: 10/10000, score: 0, time: 1
episode: 11/10000, score: 0, time: 3
episode: 12/10000, score: 0, time: 2
episode: 13/10000, score: 0, time: 1
episode: 14/10000, score: 0, time: 0
episode: 15/10000, score: 0, time: 1
episode: 16/10000, score: 20, time: 2
episode: 17/10000, score: 0, time: 0
episode: 1

episode: 176/10000, score: 0, time: 2
episode: 177/10000, score: 0, time: 3
episode: 178/10000, score: 0, time: 0
episode: 179/10000, score: 20, time: 2
episode: 180/10000, score: 0, time: 1
episode: 181/10000, score: 0, time: 4
episode: 182/10000, score: 0, time: 9
episode: 183/10000, score: 0, time: 1
episode: 184/10000, score: 0, time: 9
episode: 185/10000, score: 20, time: 9
episode: 186/10000, score: 0, time: 1
episode: 187/10000, score: 0, time: 8
episode: 188/10000, score: 0, time: 2
episode: 189/10000, score: 0, time: 1
episode: 190/10000, score: 0, time: 0
episode: 191/10000, score: 0, time: 2
episode: 192/10000, score: 0, time: 1
episode: 193/10000, score: 0, time: 1
episode: 194/10000, score: 0, time: 4
episode: 195/10000, score: 0, time: 1
episode: 196/10000, score: 0, time: 8
episode: 197/10000, score: 0, time: 3
episode: 198/10000, score: 0, time: 4
episode: 199/10000, score: 0, time: 4
[[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 

episode: 296/10000, score: 0, time: 2
episode: 297/10000, score: 0, time: 5
episode: 298/10000, score: 0, time: 4
episode: 299/10000, score: 0, time: 2
[[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 0 0 0 2 0 0 0 0 0 0 0 2 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 1 1 1 1 1 0 0 0 0 3]
 [3 0 0 0 0 1 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 2 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]]
[[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 0 0 0 2 0 0 0 0 0 0 0 2 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 1 1 1 1 0 0 0 0 0 3]
 [3 0 0 0 0 1 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 1 0 0 0 0 0 0 2 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]]
[[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 0 0 0 2 0 0 0 0 0 0 0 2 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 1 1 1 0 0

episode: 460/10000, score: 0, time: 0
episode: 461/10000, score: 0, time: 7
episode: 462/10000, score: 0, time: 0
episode: 463/10000, score: 0, time: 1
episode: 464/10000, score: 0, time: 5
episode: 465/10000, score: 0, time: 5
episode: 466/10000, score: 0, time: 1
episode: 467/10000, score: 0, time: 7
episode: 468/10000, score: 0, time: 0
episode: 469/10000, score: 0, time: 3
episode: 470/10000, score: 0, time: 0
episode: 471/10000, score: 0, time: 1
episode: 472/10000, score: 0, time: 1
episode: 473/10000, score: 0, time: 7
episode: 474/10000, score: 0, time: 1
episode: 475/10000, score: 20, time: 1
episode: 476/10000, score: 0, time: 5
episode: 477/10000, score: 0, time: 1
episode: 478/10000, score: 0, time: 9
episode: 479/10000, score: 0, time: 1
episode: 480/10000, score: 0, time: 0
episode: 481/10000, score: 20, time: 6
episode: 482/10000, score: 0, time: 3
episode: 483/10000, score: 0, time: 5
episode: 484/10000, score: 0, time: 7
episode: 485/10000, score: 20, time: 4
episode: 

episode: 624/10000, score: 0, time: 2
episode: 625/10000, score: 0, time: 1
episode: 626/10000, score: 0, time: 1
episode: 627/10000, score: 0, time: 0
episode: 628/10000, score: 0, time: 0
episode: 629/10000, score: 0, time: 2
episode: 630/10000, score: 0, time: 0
episode: 631/10000, score: 0, time: 1
episode: 632/10000, score: 0, time: 4
episode: 633/10000, score: 0, time: 3
episode: 634/10000, score: 0, time: 0
episode: 635/10000, score: 0, time: 0
episode: 636/10000, score: 0, time: 0
episode: 637/10000, score: 0, time: 0
episode: 638/10000, score: 0, time: 4
episode: 639/10000, score: 20, time: 5
episode: 640/10000, score: 0, time: 0
episode: 641/10000, score: 0, time: 0
episode: 642/10000, score: 0, time: 9
episode: 643/10000, score: 0, time: 3
episode: 644/10000, score: 0, time: 6
episode: 645/10000, score: 0, time: 0
episode: 646/10000, score: 0, time: 0
episode: 647/10000, score: 0, time: 0
episode: 648/10000, score: 0, time: 6
episode: 649/10000, score: 0, time: 7
episode: 65

episode: 802/10000, score: 0, time: 0
episode: 803/10000, score: 0, time: 0
episode: 804/10000, score: 0, time: 4
episode: 805/10000, score: 20, time: 6
episode: 806/10000, score: 20, time: 3
episode: 807/10000, score: 0, time: 3
episode: 808/10000, score: 0, time: 0
episode: 809/10000, score: 0, time: 5
episode: 810/10000, score: 0, time: 4
episode: 811/10000, score: 0, time: 1
episode: 812/10000, score: 0, time: 7
episode: 813/10000, score: 0, time: 4
episode: 814/10000, score: 0, time: 0
episode: 815/10000, score: 0, time: 4
episode: 816/10000, score: 0, time: 1
episode: 817/10000, score: 0, time: 3
episode: 818/10000, score: 0, time: 5
episode: 819/10000, score: 0, time: 2
episode: 820/10000, score: 0, time: 7
episode: 821/10000, score: 0, time: 0
episode: 822/10000, score: 0, time: 1
episode: 823/10000, score: 0, time: 1
episode: 824/10000, score: 0, time: 3
episode: 825/10000, score: 0, time: 2
episode: 826/10000, score: 0, time: 3
episode: 827/10000, score: 0, time: 1
episode: 8

episode: 992/10000, score: 0, time: 9
episode: 993/10000, score: 0, time: 0
episode: 994/10000, score: 0, time: 4
episode: 995/10000, score: 0, time: 0
episode: 996/10000, score: 0, time: 4
episode: 997/10000, score: 0, time: 6
episode: 998/10000, score: 0, time: 0
episode: 999/10000, score: 20, time: 5
[[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 0 0 0 0 0 0 0 0 0 0 2 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 1 1 1 1 1 1 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 2 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 2 0 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]]
episode: 1000/10000, score: 0, time: 0
episode: 1001/10000, score: 0, time: 0
episode: 1002/10000, score: 20, time: 6
episode: 1003/10000, score: 0, time: 3
episode: 1004/10000, score: 0, time: 1
episode: 1005/10000, score: 0, time: 5
episode: 1006/10000, score: 20, time: 2
episode: 1007/10000, score: 0, time: 0
episode: 1008/10000, score: 20, time: 3
episode: 1

episode: 1144/10000, score: 0, time: 0
episode: 1145/10000, score: 0, time: 3
episode: 1146/10000, score: 0, time: 2
episode: 1147/10000, score: 0, time: 2
episode: 1148/10000, score: 0, time: 4
episode: 1149/10000, score: 0, time: 1
episode: 1150/10000, score: 0, time: 0
episode: 1151/10000, score: 0, time: 0
episode: 1152/10000, score: 0, time: 1
episode: 1153/10000, score: 0, time: 0
episode: 1154/10000, score: 0, time: 3
episode: 1155/10000, score: 20, time: 6
episode: 1156/10000, score: 0, time: 5
episode: 1157/10000, score: 20, time: 5
episode: 1158/10000, score: 0, time: 6
episode: 1159/10000, score: 0, time: 0
episode: 1160/10000, score: 0, time: 3
episode: 1161/10000, score: 0, time: 2
episode: 1162/10000, score: 0, time: 2
episode: 1163/10000, score: 0, time: 6
episode: 1164/10000, score: 0, time: 3
episode: 1165/10000, score: 0, time: 6
episode: 1166/10000, score: 0, time: 0
episode: 1167/10000, score: 0, time: 5
episode: 1168/10000, score: 0, time: 4
episode: 1169/10000, sc

episode: 1312/10000, score: 0, time: 4
episode: 1313/10000, score: 0, time: 4
episode: 1314/10000, score: 0, time: 0
episode: 1315/10000, score: 0, time: 0
episode: 1316/10000, score: 0, time: 4
episode: 1317/10000, score: 0, time: 4
episode: 1318/10000, score: 0, time: 3
episode: 1319/10000, score: 0, time: 3
episode: 1320/10000, score: 0, time: 7
episode: 1321/10000, score: 0, time: 5
episode: 1322/10000, score: 0, time: 4
episode: 1323/10000, score: 0, time: 0
episode: 1324/10000, score: 0, time: 5
episode: 1325/10000, score: 40, time: 6
episode: 1326/10000, score: 0, time: 2
episode: 1327/10000, score: 0, time: 0
episode: 1328/10000, score: 0, time: 7
episode: 1329/10000, score: 0, time: 7
episode: 1330/10000, score: 0, time: 0
episode: 1331/10000, score: 0, time: 0
episode: 1332/10000, score: 0, time: 2
episode: 1333/10000, score: 0, time: 2
episode: 1334/10000, score: 0, time: 4
episode: 1335/10000, score: 0, time: 6
episode: 1336/10000, score: 0, time: 1
episode: 1337/10000, sco

episode: 1464/10000, score: 0, time: 6
episode: 1465/10000, score: 20, time: 7
episode: 1466/10000, score: 0, time: 1
episode: 1467/10000, score: 0, time: 4
episode: 1468/10000, score: 0, time: 1
episode: 1469/10000, score: 0, time: 4
episode: 1470/10000, score: 20, time: 4
episode: 1471/10000, score: 0, time: 2
episode: 1472/10000, score: 0, time: 6
episode: 1473/10000, score: 20, time: 5
episode: 1474/10000, score: 0, time: 2
episode: 1475/10000, score: 0, time: 1
episode: 1476/10000, score: 0, time: 8
episode: 1477/10000, score: 0, time: 3
episode: 1478/10000, score: 0, time: 1
episode: 1479/10000, score: 0, time: 4
episode: 1480/10000, score: 0, time: 2
episode: 1481/10000, score: 0, time: 5
episode: 1482/10000, score: 20, time: 7
episode: 1483/10000, score: 0, time: 0
episode: 1484/10000, score: 0, time: 2
episode: 1485/10000, score: 20, time: 4
episode: 1486/10000, score: 0, time: 5
episode: 1487/10000, score: 0, time: 4
episode: 1488/10000, score: 0, time: 1
episode: 1489/10000,

episode: 1602/10000, score: 0, time: 4
episode: 1603/10000, score: 0, time: 0
episode: 1604/10000, score: 0, time: 6
episode: 1605/10000, score: 0, time: 1
episode: 1606/10000, score: 0, time: 2
episode: 1607/10000, score: 0, time: 6
episode: 1608/10000, score: 0, time: 5
episode: 1609/10000, score: 20, time: 6
episode: 1610/10000, score: 0, time: 6
episode: 1611/10000, score: 0, time: 0
episode: 1612/10000, score: 0, time: 5
episode: 1613/10000, score: 0, time: 5
episode: 1614/10000, score: 0, time: 2
episode: 1615/10000, score: 0, time: 1
episode: 1616/10000, score: 20, time: 5
episode: 1617/10000, score: 20, time: 4
episode: 1618/10000, score: 0, time: 2
episode: 1619/10000, score: 0, time: 4
episode: 1620/10000, score: 0, time: 5
episode: 1621/10000, score: 0, time: 0
episode: 1622/10000, score: 0, time: 4
episode: 1623/10000, score: 0, time: 4
episode: 1624/10000, score: 0, time: 2
episode: 1625/10000, score: 0, time: 4
episode: 1626/10000, score: 20, time: 5
episode: 1627/10000, 

episode: 1802/10000, score: 0, time: 4
episode: 1803/10000, score: 20, time: 4
episode: 1804/10000, score: 0, time: 2
episode: 1805/10000, score: 20, time: 5
episode: 1806/10000, score: 0, time: 3
episode: 1807/10000, score: 0, time: 6
episode: 1808/10000, score: 0, time: 5
episode: 1809/10000, score: 20, time: 6
episode: 1810/10000, score: 0, time: 4
episode: 1811/10000, score: 0, time: 4
episode: 1812/10000, score: 0, time: 1
episode: 1813/10000, score: 0, time: 1
episode: 1814/10000, score: 0, time: 6
episode: 1815/10000, score: 0, time: 1
episode: 1816/10000, score: 0, time: 4
episode: 1817/10000, score: 0, time: 6
episode: 1818/10000, score: 0, time: 5
episode: 1819/10000, score: 0, time: 0
episode: 1820/10000, score: 0, time: 2
episode: 1821/10000, score: 0, time: 2
episode: 1822/10000, score: 20, time: 6
episode: 1823/10000, score: 20, time: 5
episode: 1824/10000, score: 0, time: 1
episode: 1825/10000, score: 0, time: 4
episode: 1826/10000, score: 0, time: 4
episode: 1827/10000,

episode: 1996/10000, score: 0, time: 0
episode: 1997/10000, score: 0, time: 4
episode: 1998/10000, score: 0, time: 4
episode: 1999/10000, score: 0, time: 7
[[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 2 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 1 1 1 1 1 1 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 2 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 2 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]]
[[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 2 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 1 1 1 1 1 0 0 0 0 0 3]
 [3 0 0 0 1 0 0 0 0 0 0 2 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 2 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]]
[[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 2 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 1 1 1 1

episode: 2122/10000, score: 0, time: 5
episode: 2123/10000, score: 0, time: 7
episode: 2124/10000, score: 0, time: 5
episode: 2125/10000, score: 20, time: 4
episode: 2126/10000, score: 0, time: 0
episode: 2127/10000, score: 0, time: 4
episode: 2128/10000, score: 0, time: 4
episode: 2129/10000, score: 0, time: 5
episode: 2130/10000, score: 20, time: 4
episode: 2131/10000, score: 0, time: 3
episode: 2132/10000, score: 0, time: 1
episode: 2133/10000, score: 0, time: 2
episode: 2134/10000, score: 0, time: 4
episode: 2135/10000, score: 0, time: 4
episode: 2136/10000, score: 0, time: 2
episode: 2137/10000, score: 0, time: 3
episode: 2138/10000, score: 0, time: 1
episode: 2139/10000, score: 0, time: 5
episode: 2140/10000, score: 0, time: 4
episode: 2141/10000, score: 0, time: 4
episode: 2142/10000, score: 0, time: 3
episode: 2143/10000, score: 0, time: 4
episode: 2144/10000, score: 0, time: 6
episode: 2145/10000, score: 0, time: 4
episode: 2146/10000, score: 0, time: 4
episode: 2147/10000, sc

episode: 2298/10000, score: 0, time: 6
episode: 2299/10000, score: 0, time: 6
[[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 2 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 1 1 1 1 1 1 0 0 0 0 3]
 [3 0 0 0 0 0 2 0 0 2 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]]
[[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 2 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 1 1 1 1 1 1 0 0 0 0 3]
 [3 0 0 0 0 0 2 0 0 2 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]]
episode: 2300/10000, score: 0, time: 1
episode: 2301/10000, score: 0, time: 2
episode: 2302/10000, score: 0, time: 2
episode: 2303/10000, score: 0, time: 5
episode: 2304/10000, score: 0, time: 0
episode: 2305/10000, score: 0, time: 8
episode: 2306/10000, score

episode: 2458/10000, score: 0, time: 4
episode: 2459/10000, score: 0, time: 5
episode: 2460/10000, score: 0, time: 4
episode: 2461/10000, score: 0, time: 0
episode: 2462/10000, score: 0, time: 5
episode: 2463/10000, score: 20, time: 7
episode: 2464/10000, score: 0, time: 1
episode: 2465/10000, score: 0, time: 2
episode: 2466/10000, score: 0, time: 4
episode: 2467/10000, score: 0, time: 4
episode: 2468/10000, score: 0, time: 4
episode: 2469/10000, score: 0, time: 1
episode: 2470/10000, score: 0, time: 4
episode: 2471/10000, score: 0, time: 4
episode: 2472/10000, score: 0, time: 5
episode: 2473/10000, score: 0, time: 5
episode: 2474/10000, score: 0, time: 6
episode: 2475/10000, score: 0, time: 0
episode: 2476/10000, score: 0, time: 5
episode: 2477/10000, score: 0, time: 2
episode: 2478/10000, score: 0, time: 4
episode: 2479/10000, score: 20, time: 7
episode: 2480/10000, score: 0, time: 5
episode: 2481/10000, score: 0, time: 3
episode: 2482/10000, score: 0, time: 5
episode: 2483/10000, sc

episode: 2602/10000, score: 0, time: 4
episode: 2603/10000, score: 0, time: 4
episode: 2604/10000, score: 0, time: 2
episode: 2605/10000, score: 0, time: 4
episode: 2606/10000, score: 0, time: 5
episode: 2607/10000, score: 0, time: 3
episode: 2608/10000, score: 0, time: 4
episode: 2609/10000, score: 0, time: 4
episode: 2610/10000, score: 0, time: 0
episode: 2611/10000, score: 0, time: 2
episode: 2612/10000, score: 0, time: 7
episode: 2613/10000, score: 0, time: 4
episode: 2614/10000, score: 0, time: 1
episode: 2615/10000, score: 0, time: 1
episode: 2616/10000, score: 0, time: 3
episode: 2617/10000, score: 0, time: 4
episode: 2618/10000, score: 0, time: 0
episode: 2619/10000, score: 20, time: 4
episode: 2620/10000, score: 0, time: 4
episode: 2621/10000, score: 0, time: 4
episode: 2622/10000, score: 20, time: 4
episode: 2623/10000, score: 0, time: 3
episode: 2624/10000, score: 0, time: 1
episode: 2625/10000, score: 0, time: 5
episode: 2626/10000, score: 0, time: 0
episode: 2627/10000, sc

episode: 2762/10000, score: 0, time: 2
episode: 2763/10000, score: 0, time: 4
episode: 2764/10000, score: 0, time: 4
episode: 2765/10000, score: 0, time: 5
episode: 2766/10000, score: 0, time: 4
episode: 2767/10000, score: 0, time: 5
episode: 2768/10000, score: 0, time: 4
episode: 2769/10000, score: 0, time: 2
episode: 2770/10000, score: 0, time: 5
episode: 2771/10000, score: 0, time: 4
episode: 2772/10000, score: 0, time: 4
episode: 2773/10000, score: 0, time: 4
episode: 2774/10000, score: 0, time: 4
episode: 2775/10000, score: 0, time: 4
episode: 2776/10000, score: 0, time: 5
episode: 2777/10000, score: 0, time: 4
episode: 2778/10000, score: 20, time: 3
episode: 2779/10000, score: 0, time: 4
episode: 2780/10000, score: 0, time: 4
episode: 2781/10000, score: 0, time: 4
episode: 2782/10000, score: 0, time: 4
episode: 2783/10000, score: 0, time: 4
episode: 2784/10000, score: 20, time: 5
episode: 2785/10000, score: 0, time: 4
episode: 2786/10000, score: 0, time: 2
episode: 2787/10000, sc

episode: 2914/10000, score: 0, time: 4
episode: 2915/10000, score: 0, time: 4
episode: 2916/10000, score: 0, time: 4
episode: 2917/10000, score: 0, time: 4
episode: 2918/10000, score: 0, time: 4
episode: 2919/10000, score: 0, time: 0
episode: 2920/10000, score: 0, time: 6
episode: 2921/10000, score: 0, time: 3
episode: 2922/10000, score: 0, time: 6
episode: 2923/10000, score: 0, time: 4
episode: 2924/10000, score: 0, time: 4
episode: 2925/10000, score: 20, time: 5
episode: 2926/10000, score: 0, time: 4
episode: 2927/10000, score: 0, time: 2
episode: 2928/10000, score: 0, time: 5
episode: 2929/10000, score: 0, time: 6
episode: 2930/10000, score: 20, time: 5
episode: 2931/10000, score: 0, time: 3
episode: 2932/10000, score: 0, time: 4
episode: 2933/10000, score: 0, time: 0
episode: 2934/10000, score: 0, time: 4
episode: 2935/10000, score: 0, time: 4
episode: 2936/10000, score: 0, time: 4
episode: 2937/10000, score: 0, time: 4
episode: 2938/10000, score: 0, time: 5
episode: 2939/10000, sc

episode: 3074/10000, score: 0, time: 6
episode: 3075/10000, score: 0, time: 4
episode: 3076/10000, score: 0, time: 4
episode: 3077/10000, score: 0, time: 4
episode: 3078/10000, score: 20, time: 5
episode: 3079/10000, score: 0, time: 3
episode: 3080/10000, score: 0, time: 5
episode: 3081/10000, score: 0, time: 4
episode: 3082/10000, score: 0, time: 1
episode: 3083/10000, score: 0, time: 4
episode: 3084/10000, score: 0, time: 5
episode: 3085/10000, score: 20, time: 2
episode: 3086/10000, score: 0, time: 3
episode: 3087/10000, score: 0, time: 3
episode: 3088/10000, score: 0, time: 4
episode: 3089/10000, score: 0, time: 4
episode: 3090/10000, score: 0, time: 4
episode: 3091/10000, score: 20, time: 4
episode: 3092/10000, score: 0, time: 4
episode: 3093/10000, score: 0, time: 5
episode: 3094/10000, score: 0, time: 4
episode: 3095/10000, score: 20, time: 5
episode: 3096/10000, score: 0, time: 4
episode: 3097/10000, score: 20, time: 5
episode: 3098/10000, score: 20, time: 6
episode: 3099/10000

episode: 3202/10000, score: 0, time: 5
episode: 3203/10000, score: 0, time: 6
episode: 3204/10000, score: 0, time: 4
episode: 3205/10000, score: 0, time: 4
episode: 3206/10000, score: 0, time: 4
episode: 3207/10000, score: 0, time: 4
episode: 3208/10000, score: 0, time: 4
episode: 3209/10000, score: 0, time: 4
episode: 3210/10000, score: 0, time: 4
episode: 3211/10000, score: 0, time: 4
episode: 3212/10000, score: 0, time: 4
episode: 3213/10000, score: 0, time: 4
episode: 3214/10000, score: 0, time: 4
episode: 3215/10000, score: 0, time: 1
episode: 3216/10000, score: 0, time: 4
episode: 3217/10000, score: 0, time: 3
episode: 3218/10000, score: 0, time: 0
episode: 3219/10000, score: 0, time: 1
episode: 3220/10000, score: 0, time: 4
episode: 3221/10000, score: 0, time: 4
episode: 3222/10000, score: 0, time: 3
episode: 3223/10000, score: 0, time: 4
episode: 3224/10000, score: 0, time: 4
episode: 3225/10000, score: 0, time: 4
episode: 3226/10000, score: 0, time: 4
episode: 3227/10000, scor

episode: 3354/10000, score: 0, time: 5
episode: 3355/10000, score: 0, time: 4
episode: 3356/10000, score: 0, time: 2
episode: 3357/10000, score: 20, time: 5
episode: 3358/10000, score: 0, time: 3
episode: 3359/10000, score: 0, time: 6
episode: 3360/10000, score: 0, time: 4
episode: 3361/10000, score: 0, time: 4
episode: 3362/10000, score: 0, time: 4
episode: 3363/10000, score: 40, time: 6
episode: 3364/10000, score: 0, time: 4
episode: 3365/10000, score: 0, time: 4
episode: 3366/10000, score: 0, time: 1
episode: 3367/10000, score: 0, time: 7
episode: 3368/10000, score: 0, time: 3
episode: 3369/10000, score: 0, time: 4
episode: 3370/10000, score: 0, time: 4
episode: 3371/10000, score: 0, time: 5
episode: 3372/10000, score: 0, time: 5
episode: 3373/10000, score: 0, time: 4
episode: 3374/10000, score: 0, time: 3
episode: 3375/10000, score: 0, time: 4
episode: 3376/10000, score: 0, time: 5
episode: 3377/10000, score: 0, time: 3
episode: 3378/10000, score: 0, time: 0
episode: 3379/10000, sc

episode: 3502/10000, score: 0, time: 3
episode: 3503/10000, score: 0, time: 5
episode: 3504/10000, score: 20, time: 4
episode: 3505/10000, score: 0, time: 4
episode: 3506/10000, score: 0, time: 2
episode: 3507/10000, score: 0, time: 4
episode: 3508/10000, score: 0, time: 4
episode: 3509/10000, score: 0, time: 4
episode: 3510/10000, score: 0, time: 3
episode: 3511/10000, score: 0, time: 4
episode: 3512/10000, score: 0, time: 5
episode: 3513/10000, score: 0, time: 4
episode: 3514/10000, score: 0, time: 5
episode: 3515/10000, score: 0, time: 2
episode: 3516/10000, score: 0, time: 5
episode: 3517/10000, score: 20, time: 4
episode: 3518/10000, score: 0, time: 1
episode: 3519/10000, score: 0, time: 4
episode: 3520/10000, score: 0, time: 4
episode: 3521/10000, score: 0, time: 4
episode: 3522/10000, score: 0, time: 0
episode: 3523/10000, score: 0, time: 4
episode: 3524/10000, score: 0, time: 4
episode: 3525/10000, score: 0, time: 4
episode: 3526/10000, score: 0, time: 0
episode: 3527/10000, sc

episode: 3662/10000, score: 0, time: 5
episode: 3663/10000, score: 0, time: 4
episode: 3664/10000, score: 0, time: 4
episode: 3665/10000, score: 20, time: 4
episode: 3666/10000, score: 0, time: 5
episode: 3667/10000, score: 0, time: 4
episode: 3668/10000, score: 0, time: 5
episode: 3669/10000, score: 0, time: 5
episode: 3670/10000, score: 20, time: 3
episode: 3671/10000, score: 0, time: 6
episode: 3672/10000, score: 0, time: 5
episode: 3673/10000, score: 0, time: 4
episode: 3674/10000, score: 0, time: 1
episode: 3675/10000, score: 0, time: 5
episode: 3676/10000, score: 0, time: 4
episode: 3677/10000, score: 0, time: 3
episode: 3678/10000, score: 0, time: 4
episode: 3679/10000, score: 0, time: 4
episode: 3680/10000, score: 0, time: 2
episode: 3681/10000, score: 0, time: 1
episode: 3682/10000, score: 20, time: 6
episode: 3683/10000, score: 0, time: 4
episode: 3684/10000, score: 0, time: 3
episode: 3685/10000, score: 0, time: 4
episode: 3686/10000, score: 0, time: 4
episode: 3687/10000, s

episode: 3802/10000, score: 0, time: 5
episode: 3803/10000, score: 0, time: 4
episode: 3804/10000, score: 0, time: 5
episode: 3805/10000, score: 0, time: 5
episode: 3806/10000, score: 0, time: 4
episode: 3807/10000, score: 0, time: 4
episode: 3808/10000, score: 0, time: 0
episode: 3809/10000, score: 0, time: 6
episode: 3810/10000, score: 0, time: 4
episode: 3811/10000, score: 0, time: 4
episode: 3812/10000, score: 20, time: 4
episode: 3813/10000, score: 0, time: 4
episode: 3814/10000, score: 0, time: 1
episode: 3815/10000, score: 0, time: 4
episode: 3816/10000, score: 0, time: 4
episode: 3817/10000, score: 0, time: 4
episode: 3818/10000, score: 0, time: 0
episode: 3819/10000, score: 0, time: 4
episode: 3820/10000, score: 0, time: 4
episode: 3821/10000, score: 0, time: 5
episode: 3822/10000, score: 0, time: 5
episode: 3823/10000, score: 0, time: 4
episode: 3824/10000, score: 0, time: 4
episode: 3825/10000, score: 0, time: 6
episode: 3826/10000, score: 0, time: 4
episode: 3827/10000, sco

episode: 3970/10000, score: 0, time: 4
episode: 3971/10000, score: 0, time: 6
episode: 3972/10000, score: 0, time: 4
episode: 3973/10000, score: 0, time: 4
episode: 3974/10000, score: 0, time: 4
episode: 3975/10000, score: 0, time: 4
episode: 3976/10000, score: 0, time: 0
episode: 3977/10000, score: 0, time: 4
episode: 3978/10000, score: 0, time: 4
episode: 3979/10000, score: 0, time: 5
episode: 3980/10000, score: 0, time: 4
episode: 3981/10000, score: 0, time: 4
episode: 3982/10000, score: 0, time: 4
episode: 3983/10000, score: 0, time: 4
episode: 3984/10000, score: 0, time: 5
episode: 3985/10000, score: 0, time: 4
episode: 3986/10000, score: 0, time: 4
episode: 3987/10000, score: 0, time: 4
episode: 3988/10000, score: 0, time: 4
episode: 3989/10000, score: 0, time: 5
episode: 3990/10000, score: 20, time: 4
episode: 3991/10000, score: 20, time: 4
episode: 3992/10000, score: 0, time: 5
episode: 3993/10000, score: 40, time: 6
episode: 3994/10000, score: 0, time: 4
episode: 3995/10000, s

episode: 4122/10000, score: 0, time: 4
episode: 4123/10000, score: 0, time: 4
episode: 4124/10000, score: 0, time: 4
episode: 4125/10000, score: 0, time: 4
episode: 4126/10000, score: 0, time: 6
episode: 4127/10000, score: 0, time: 4
episode: 4128/10000, score: 0, time: 5
episode: 4129/10000, score: 0, time: 4
episode: 4130/10000, score: 0, time: 3
episode: 4131/10000, score: 0, time: 0
episode: 4132/10000, score: 0, time: 5
episode: 4133/10000, score: 20, time: 4
episode: 4134/10000, score: 0, time: 0
episode: 4135/10000, score: 0, time: 4
episode: 4136/10000, score: 0, time: 4
episode: 4137/10000, score: 0, time: 4
episode: 4138/10000, score: 0, time: 6
episode: 4139/10000, score: 0, time: 1
episode: 4140/10000, score: 0, time: 6
episode: 4141/10000, score: 0, time: 5
episode: 4142/10000, score: 0, time: 4
episode: 4143/10000, score: 0, time: 4
episode: 4144/10000, score: 0, time: 4
episode: 4145/10000, score: 20, time: 4
episode: 4146/10000, score: 0, time: 1
episode: 4147/10000, sc

episode: 4282/10000, score: 0, time: 4
episode: 4283/10000, score: 0, time: 4
episode: 4284/10000, score: 0, time: 4
episode: 4285/10000, score: 0, time: 0
episode: 4286/10000, score: 0, time: 4
episode: 4287/10000, score: 20, time: 4
episode: 4288/10000, score: 20, time: 4
episode: 4289/10000, score: 0, time: 4
episode: 4290/10000, score: 0, time: 5
episode: 4291/10000, score: 20, time: 5
episode: 4292/10000, score: 0, time: 4
episode: 4293/10000, score: 0, time: 0
episode: 4294/10000, score: 0, time: 4
episode: 4295/10000, score: 20, time: 2
episode: 4296/10000, score: 0, time: 4
episode: 4297/10000, score: 40, time: 7
episode: 4298/10000, score: 0, time: 4
episode: 4299/10000, score: 0, time: 4
[[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 2 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 1 1 1 1 1 1 0 0 0 0 3]
 [3 2 0 0 0 0 0 0 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 2 0 0 0 0 0 0 3]
 [3 0 0 0 0 0 0 0 0 0 0 0 0 0

episode: 4450/10000, score: 20, time: 5
episode: 4451/10000, score: 0, time: 4
episode: 4452/10000, score: 0, time: 4
episode: 4453/10000, score: 20, time: 5
episode: 4454/10000, score: 0, time: 1
episode: 4455/10000, score: 0, time: 4
episode: 4456/10000, score: 0, time: 5
episode: 4457/10000, score: 20, time: 4
episode: 4458/10000, score: 0, time: 4
episode: 4459/10000, score: 0, time: 5
episode: 4460/10000, score: 0, time: 4
episode: 4461/10000, score: 0, time: 0
episode: 4462/10000, score: 0, time: 4
episode: 4463/10000, score: 0, time: 4
episode: 4464/10000, score: 0, time: 4
episode: 4465/10000, score: 0, time: 5
episode: 4466/10000, score: 0, time: 4
episode: 4467/10000, score: 40, time: 5
episode: 4468/10000, score: 0, time: 4
episode: 4469/10000, score: 20, time: 4
episode: 4470/10000, score: 0, time: 4
episode: 4471/10000, score: 0, time: 4
episode: 4472/10000, score: 0, time: 4
episode: 4473/10000, score: 0, time: 5
episode: 4474/10000, score: 0, time: 4
episode: 4475/10000,

episode: 4610/10000, score: 0, time: 4
episode: 4611/10000, score: 0, time: 4
episode: 4612/10000, score: 0, time: 5
episode: 4613/10000, score: 0, time: 4
episode: 4614/10000, score: 0, time: 5
episode: 4615/10000, score: 0, time: 2
episode: 4616/10000, score: 0, time: 5
episode: 4617/10000, score: 0, time: 5
episode: 4618/10000, score: 0, time: 4
episode: 4619/10000, score: 0, time: 4
episode: 4620/10000, score: 0, time: 4
episode: 4621/10000, score: 40, time: 4
episode: 4622/10000, score: 0, time: 4
episode: 4623/10000, score: 0, time: 3
episode: 4624/10000, score: 0, time: 5
episode: 4625/10000, score: 20, time: 4
episode: 4626/10000, score: 0, time: 5
episode: 4627/10000, score: 0, time: 4
episode: 4628/10000, score: 0, time: 4
episode: 4629/10000, score: 0, time: 4
episode: 4630/10000, score: 0, time: 4
episode: 4631/10000, score: 0, time: 4
episode: 4632/10000, score: 0, time: 4
episode: 4633/10000, score: 0, time: 4
episode: 4634/10000, score: 0, time: 4
episode: 4635/10000, sc

episode: 4770/10000, score: 0, time: 4
episode: 4771/10000, score: 0, time: 4
episode: 4772/10000, score: 0, time: 4
episode: 4773/10000, score: 20, time: 5
episode: 4774/10000, score: 0, time: 4
episode: 4775/10000, score: 0, time: 4
episode: 4776/10000, score: 40, time: 5
episode: 4777/10000, score: 0, time: 4
episode: 4778/10000, score: 20, time: 4
episode: 4779/10000, score: 0, time: 5
episode: 4780/10000, score: 0, time: 4
episode: 4781/10000, score: 0, time: 4
episode: 4782/10000, score: 0, time: 4
episode: 4783/10000, score: 0, time: 4
episode: 4784/10000, score: 0, time: 5
episode: 4785/10000, score: 0, time: 4
episode: 4786/10000, score: 0, time: 4
episode: 4787/10000, score: 0, time: 4
episode: 4788/10000, score: 0, time: 4
episode: 4789/10000, score: 0, time: 4
episode: 4790/10000, score: 0, time: 4
episode: 4791/10000, score: 0, time: 4
episode: 4792/10000, score: 0, time: 4
episode: 4793/10000, score: 0, time: 4
episode: 4794/10000, score: 0, time: 4
episode: 4795/10000, s